/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zhang' at '17/08/02 11:04' with Gradle 2.14.1
 *
 * @author zhang, @date 17/08/02 11:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
