#共通
cpp:
  messages:
    basenames: classpath:ErrorResources, classpath:ValidationMessages
  items:
    basenames: classpath:ItemResources.properties,  classpath:ItemResources.properties

#指定bean所在包
#指定映射文件
mybatis:
  type-aliases-package: jp.co.drm.ccp.base.integration.mybatis.entity, jp.co.drm.ccp.web.integration.mybatis.dto
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-Locations: classpath*:jp/co/drm/ccp/**/integration/mybatis/sqlmap/*.xml
  #classpath: 該当プロジェクトのclasspath
  #classpath*: 全てのclasspath「依頼ライブラリJARのclasspathを含む」
  #mapper-Locations:
  #   - classpath*:jp/co/drm/ccp/web/integration/mybatis/sqlmap/*.xml
  #   - classpath*:jp/co/drm/ccp/base/integration/mybatis/sqlmap/*.xml

# spring.profiles.activeにアクティブなプロファイルを指定する
spring:
  mvc:
   view:
    prefix: /webapp
    suffix: html
  profiles:
    active: dev
  messages:
    basename: msg
    cache-seconds: -1
    encoding: UTF-8

# "---"でプロファイルを区切る
# spring.profilesにプロファイル名を書く
---
#「開発環境」
spring:
  profiles: dev
---
#「テスト環境」
spring:
  profiles: test
---
#「本番環境」
spring:
  profiles: production


