server:
  port: 8080  #配置程序端口，默认为8080
  context-path: /
  session:
    timeout: 10800 #用户绘画session过期时间，以秒为单位

mail:
  fromMail:
    addr: xxoo@xxoo.com
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://192.168.81.31:3308/wms?useSSL=false
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #username: root   rootユーザ:リモート権限無し
    username: zhangw
    password: zhangw
  mvc:
    favicon:
      enabled: false
  rabbitmq:
    host: 192.168.81.31
    port: 5672
    username: test
    password: test

  mail:
    host: 192.168.81.31
    port: 25
    username: xxoo@xxoo.com
    password: xxoo
    default-encoding: UTF-8

#logging:
#  level:
#    jdbc: OFF

logging:
  level:
    jdbc:
     sqlonly: DEBUG
     sqltiming: INFO
     audit: INFO
     resultset: ERROR
     resultsettable: ERROR
     connection: DEBUG

