package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;

public class MstCorporationKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_corporation.CORPORATION_NO
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String corporationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_corporation.DEPART_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String departCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_corporation.DIVISION_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String divisionCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_corporation.CORPORATION_NO
     *
     * @return the value of mst_corporation.CORPORATION_NO
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getCorporationNo() {
        return corporationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_corporation.CORPORATION_NO
     *
     * @param corporationNo the value for mst_corporation.CORPORATION_NO
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setCorporationNo(String corporationNo) {
        this.corporationNo = corporationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_corporation.DEPART_CD
     *
     * @return the value of mst_corporation.DEPART_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getDepartCd() {
        return departCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_corporation.DEPART_CD
     *
     * @param departCd the value for mst_corporation.DEPART_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setDepartCd(String departCd) {
        this.departCd = departCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_corporation.DIVISION_CD
     *
     * @return the value of mst_corporation.DIVISION_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getDivisionCd() {
        return divisionCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_corporation.DIVISION_CD
     *
     * @param divisionCd the value for mst_corporation.DIVISION_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setDivisionCd(String divisionCd) {
        this.divisionCd = divisionCd;
    }
}