package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;

public class MstGroupRoleKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group_role.GROUP_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group_role.MODULE_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String moduleCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group_role.GROUP_ID
     *
     * @return the value of mst_group_role.GROUP_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group_role.GROUP_ID
     *
     * @param groupId the value for mst_group_role.GROUP_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group_role.MODULE_CD
     *
     * @return the value of mst_group_role.MODULE_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getModuleCd() {
        return moduleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group_role.MODULE_CD
     *
     * @param moduleCd the value for mst_group_role.MODULE_CD
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setModuleCd(String moduleCd) {
        this.moduleCd = moduleCd;
    }
}