package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class MstGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group.GROUP_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group.GROUP_NM
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String groupNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group.REG_USER_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String regUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private Date regDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private String updUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_group.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private Date updDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group.GROUP_ID
     *
     * @return the value of mst_group.GROUP_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group.GROUP_ID
     *
     * @param groupId the value for mst_group.GROUP_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group.GROUP_NM
     *
     * @return the value of mst_group.GROUP_NM
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getGroupNm() {
        return groupNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group.GROUP_NM
     *
     * @param groupNm the value for mst_group.GROUP_NM
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setGroupNm(String groupNm) {
        this.groupNm = groupNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group.REG_USER_ID
     *
     * @return the value of mst_group.REG_USER_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getRegUserId() {
        return regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group.REG_USER_ID
     *
     * @param regUserId the value for mst_group.REG_USER_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setRegUserId(String regUserId) {
        this.regUserId = regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group.REG_DATE_TIME
     *
     * @return the value of mst_group.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public Date getRegDateTime() {
        return regDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group.REG_DATE_TIME
     *
     * @param regDateTime the value for mst_group.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setRegDateTime(Date regDateTime) {
        this.regDateTime = regDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group.UPD_USER_ID
     *
     * @return the value of mst_group.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getUpdUserId() {
        return updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group.UPD_USER_ID
     *
     * @param updUserId the value for mst_group.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_group.UPD_DATE_TIME
     *
     * @return the value of mst_group.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public Date getUpdDateTime() {
        return updDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_group.UPD_DATE_TIME
     *
     * @param updDateTime the value for mst_group.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setUpdDateTime(Date updDateTime) {
        this.updDateTime = updDateTime;
    }
}