package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MstModuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public MstModuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleCdIsNull() {
            addCriterion("ROLE_CD is null");
            return (Criteria) this;
        }

        public Criteria andRoleCdIsNotNull() {
            addCriterion("ROLE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCdEqualTo(String value) {
            addCriterion("ROLE_CD =", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotEqualTo(String value) {
            addCriterion("ROLE_CD <>", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdGreaterThan(String value) {
            addCriterion("ROLE_CD >", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_CD >=", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdLessThan(String value) {
            addCriterion("ROLE_CD <", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdLessThanOrEqualTo(String value) {
            addCriterion("ROLE_CD <=", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdLike(String value) {
            addCriterion("ROLE_CD like", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotLike(String value) {
            addCriterion("ROLE_CD not like", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdIn(List<String> values) {
            addCriterion("ROLE_CD in", values, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotIn(List<String> values) {
            addCriterion("ROLE_CD not in", values, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdBetween(String value1, String value2) {
            addCriterion("ROLE_CD between", value1, value2, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotBetween(String value1, String value2) {
            addCriterion("ROLE_CD not between", value1, value2, "roleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdIsNull() {
            addCriterion("MODULE_CD is null");
            return (Criteria) this;
        }

        public Criteria andModuleCdIsNotNull() {
            addCriterion("MODULE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andModuleCdEqualTo(String value) {
            addCriterion("MODULE_CD =", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdNotEqualTo(String value) {
            addCriterion("MODULE_CD <>", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdGreaterThan(String value) {
            addCriterion("MODULE_CD >", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_CD >=", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdLessThan(String value) {
            addCriterion("MODULE_CD <", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdLessThanOrEqualTo(String value) {
            addCriterion("MODULE_CD <=", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdLike(String value) {
            addCriterion("MODULE_CD like", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdNotLike(String value) {
            addCriterion("MODULE_CD not like", value, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdIn(List<String> values) {
            addCriterion("MODULE_CD in", values, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdNotIn(List<String> values) {
            addCriterion("MODULE_CD not in", values, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdBetween(String value1, String value2) {
            addCriterion("MODULE_CD between", value1, value2, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleCdNotBetween(String value1, String value2) {
            addCriterion("MODULE_CD not between", value1, value2, "moduleCd");
            return (Criteria) this;
        }

        public Criteria andModuleNmIsNull() {
            addCriterion("MODULE_NM is null");
            return (Criteria) this;
        }

        public Criteria andModuleNmIsNotNull() {
            addCriterion("MODULE_NM is not null");
            return (Criteria) this;
        }

        public Criteria andModuleNmEqualTo(String value) {
            addCriterion("MODULE_NM =", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmNotEqualTo(String value) {
            addCriterion("MODULE_NM <>", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmGreaterThan(String value) {
            addCriterion("MODULE_NM >", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_NM >=", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmLessThan(String value) {
            addCriterion("MODULE_NM <", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmLessThanOrEqualTo(String value) {
            addCriterion("MODULE_NM <=", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmLike(String value) {
            addCriterion("MODULE_NM like", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmNotLike(String value) {
            addCriterion("MODULE_NM not like", value, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmIn(List<String> values) {
            addCriterion("MODULE_NM in", values, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmNotIn(List<String> values) {
            addCriterion("MODULE_NM not in", values, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmBetween(String value1, String value2) {
            addCriterion("MODULE_NM between", value1, value2, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andModuleNmNotBetween(String value1, String value2) {
            addCriterion("MODULE_NM not between", value1, value2, "moduleNm");
            return (Criteria) this;
        }

        public Criteria andRegUserIdIsNull() {
            addCriterion("REG_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegUserIdIsNotNull() {
            addCriterion("REG_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegUserIdEqualTo(String value) {
            addCriterion("REG_USER_ID =", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotEqualTo(String value) {
            addCriterion("REG_USER_ID <>", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdGreaterThan(String value) {
            addCriterion("REG_USER_ID >", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("REG_USER_ID >=", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdLessThan(String value) {
            addCriterion("REG_USER_ID <", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdLessThanOrEqualTo(String value) {
            addCriterion("REG_USER_ID <=", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdLike(String value) {
            addCriterion("REG_USER_ID like", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotLike(String value) {
            addCriterion("REG_USER_ID not like", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdIn(List<String> values) {
            addCriterion("REG_USER_ID in", values, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotIn(List<String> values) {
            addCriterion("REG_USER_ID not in", values, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdBetween(String value1, String value2) {
            addCriterion("REG_USER_ID between", value1, value2, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotBetween(String value1, String value2) {
            addCriterion("REG_USER_ID not between", value1, value2, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeIsNull() {
            addCriterion("REG_DATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeIsNotNull() {
            addCriterion("REG_DATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeEqualTo(Date value) {
            addCriterion("REG_DATE_TIME =", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeNotEqualTo(Date value) {
            addCriterion("REG_DATE_TIME <>", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeGreaterThan(Date value) {
            addCriterion("REG_DATE_TIME >", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DATE_TIME >=", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeLessThan(Date value) {
            addCriterion("REG_DATE_TIME <", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("REG_DATE_TIME <=", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeIn(List<Date> values) {
            addCriterion("REG_DATE_TIME in", values, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeNotIn(List<Date> values) {
            addCriterion("REG_DATE_TIME not in", values, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeBetween(Date value1, Date value2) {
            addCriterion("REG_DATE_TIME between", value1, value2, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("REG_DATE_TIME not between", value1, value2, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNull() {
            addCriterion("UPD_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNotNull() {
            addCriterion("UPD_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdEqualTo(String value) {
            addCriterion("UPD_USER_ID =", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotEqualTo(String value) {
            addCriterion("UPD_USER_ID <>", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThan(String value) {
            addCriterion("UPD_USER_ID >", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPD_USER_ID >=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThan(String value) {
            addCriterion("UPD_USER_ID <", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPD_USER_ID <=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLike(String value) {
            addCriterion("UPD_USER_ID like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotLike(String value) {
            addCriterion("UPD_USER_ID not like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIn(List<String> values) {
            addCriterion("UPD_USER_ID in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotIn(List<String> values) {
            addCriterion("UPD_USER_ID not in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdBetween(String value1, String value2) {
            addCriterion("UPD_USER_ID between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("UPD_USER_ID not between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeIsNull() {
            addCriterion("UPD_DATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeIsNotNull() {
            addCriterion("UPD_DATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME =", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeNotEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME <>", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeGreaterThan(Date value) {
            addCriterion("UPD_DATE_TIME >", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME >=", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeLessThan(Date value) {
            addCriterion("UPD_DATE_TIME <", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME <=", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeIn(List<Date> values) {
            addCriterion("UPD_DATE_TIME in", values, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeNotIn(List<Date> values) {
            addCriterion("UPD_DATE_TIME not in", values, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeBetween(Date value1, Date value2) {
            addCriterion("UPD_DATE_TIME between", value1, value2, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DATE_TIME not between", value1, value2, "updDateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_module
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 18 19:42:30 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}