package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;

public class MstModuleKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_module.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String roleCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_module.MODULE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String moduleCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_module
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_module.ROLE_CD
     *
     * @return the value of mst_module.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_module.ROLE_CD
     *
     * @param roleCd the value for mst_module.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_module.MODULE_CD
     *
     * @return the value of mst_module.MODULE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getModuleCd() {
        return moduleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_module.MODULE_CD
     *
     * @param moduleCd the value for mst_module.MODULE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setModuleCd(String moduleCd) {
        this.moduleCd = moduleCd;
    }
}