package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class MstRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_role.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String roleCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_role.ROLE_NM
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String roleNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_role.REG_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String regUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_role.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private Date regDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_role.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String updUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_role.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private Date updDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_role
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_role.ROLE_CD
     *
     * @return the value of mst_role.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_role.ROLE_CD
     *
     * @param roleCd the value for mst_role.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_role.ROLE_NM
     *
     * @return the value of mst_role.ROLE_NM
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getRoleNm() {
        return roleNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_role.ROLE_NM
     *
     * @param roleNm the value for mst_role.ROLE_NM
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRoleNm(String roleNm) {
        this.roleNm = roleNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_role.REG_USER_ID
     *
     * @return the value of mst_role.REG_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getRegUserId() {
        return regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_role.REG_USER_ID
     *
     * @param regUserId the value for mst_role.REG_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRegUserId(String regUserId) {
        this.regUserId = regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_role.REG_DATE_TIME
     *
     * @return the value of mst_role.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public Date getRegDateTime() {
        return regDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_role.REG_DATE_TIME
     *
     * @param regDateTime the value for mst_role.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRegDateTime(Date regDateTime) {
        this.regDateTime = regDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_role.UPD_USER_ID
     *
     * @return the value of mst_role.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getUpdUserId() {
        return updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_role.UPD_USER_ID
     *
     * @param updUserId the value for mst_role.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_role.UPD_DATE_TIME
     *
     * @return the value of mst_role.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public Date getUpdDateTime() {
        return updDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_role.UPD_DATE_TIME
     *
     * @param updDateTime the value for mst_role.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setUpdDateTime(Date updDateTime) {
        this.updDateTime = updDateTime;
    }
}