package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MstUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public MstUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNmIsNull() {
            addCriterion("USER_NM is null");
            return (Criteria) this;
        }

        public Criteria andUserNmIsNotNull() {
            addCriterion("USER_NM is not null");
            return (Criteria) this;
        }

        public Criteria andUserNmEqualTo(String value) {
            addCriterion("USER_NM =", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotEqualTo(String value) {
            addCriterion("USER_NM <>", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmGreaterThan(String value) {
            addCriterion("USER_NM >", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NM >=", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLessThan(String value) {
            addCriterion("USER_NM <", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLessThanOrEqualTo(String value) {
            addCriterion("USER_NM <=", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLike(String value) {
            addCriterion("USER_NM like", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotLike(String value) {
            addCriterion("USER_NM not like", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmIn(List<String> values) {
            addCriterion("USER_NM in", values, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotIn(List<String> values) {
            addCriterion("USER_NM not in", values, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmBetween(String value1, String value2) {
            addCriterion("USER_NM between", value1, value2, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotBetween(String value1, String value2) {
            addCriterion("USER_NM not between", value1, value2, "userNm");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("PWD is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("PWD is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("PWD =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("PWD <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("PWD >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("PWD >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("PWD <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("PWD <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("PWD like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("PWD not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("PWD in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("PWD not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("PWD between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("PWD not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("BIRTHDAY =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("BIRTHDAY <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("BIRTHDAY >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BIRTHDAY >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("BIRTHDAY <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BIRTHDAY <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("BIRTHDAY in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("BIRTHDAY not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BIRTHDAY between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BIRTHDAY not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNull() {
            addCriterion("TEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNotNull() {
            addCriterion("TEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTelNoEqualTo(String value) {
            addCriterion("TEL_NO =", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotEqualTo(String value) {
            addCriterion("TEL_NO <>", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThan(String value) {
            addCriterion("TEL_NO >", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("TEL_NO >=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThan(String value) {
            addCriterion("TEL_NO <", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThanOrEqualTo(String value) {
            addCriterion("TEL_NO <=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLike(String value) {
            addCriterion("TEL_NO like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotLike(String value) {
            addCriterion("TEL_NO not like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoIn(List<String> values) {
            addCriterion("TEL_NO in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotIn(List<String> values) {
            addCriterion("TEL_NO not in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoBetween(String value1, String value2) {
            addCriterion("TEL_NO between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotBetween(String value1, String value2) {
            addCriterion("TEL_NO not between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNull() {
            addCriterion("MOBILE_NO is null");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNotNull() {
            addCriterion("MOBILE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNoEqualTo(String value) {
            addCriterion("MOBILE_NO =", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotEqualTo(String value) {
            addCriterion("MOBILE_NO <>", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThan(String value) {
            addCriterion("MOBILE_NO >", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO >=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThan(String value) {
            addCriterion("MOBILE_NO <", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO <=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLike(String value) {
            addCriterion("MOBILE_NO like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotLike(String value) {
            addCriterion("MOBILE_NO not like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIn(List<String> values) {
            addCriterion("MOBILE_NO in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotIn(List<String> values) {
            addCriterion("MOBILE_NO not in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoBetween(String value1, String value2) {
            addCriterion("MOBILE_NO between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotBetween(String value1, String value2) {
            addCriterion("MOBILE_NO not between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andEmail1IsNull() {
            addCriterion("EMAIL1 is null");
            return (Criteria) this;
        }

        public Criteria andEmail1IsNotNull() {
            addCriterion("EMAIL1 is not null");
            return (Criteria) this;
        }

        public Criteria andEmail1EqualTo(String value) {
            addCriterion("EMAIL1 =", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotEqualTo(String value) {
            addCriterion("EMAIL1 <>", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1GreaterThan(String value) {
            addCriterion("EMAIL1 >", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1GreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL1 >=", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1LessThan(String value) {
            addCriterion("EMAIL1 <", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1LessThanOrEqualTo(String value) {
            addCriterion("EMAIL1 <=", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1Like(String value) {
            addCriterion("EMAIL1 like", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotLike(String value) {
            addCriterion("EMAIL1 not like", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1In(List<String> values) {
            addCriterion("EMAIL1 in", values, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotIn(List<String> values) {
            addCriterion("EMAIL1 not in", values, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1Between(String value1, String value2) {
            addCriterion("EMAIL1 between", value1, value2, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotBetween(String value1, String value2) {
            addCriterion("EMAIL1 not between", value1, value2, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail2IsNull() {
            addCriterion("EMAIL2 is null");
            return (Criteria) this;
        }

        public Criteria andEmail2IsNotNull() {
            addCriterion("EMAIL2 is not null");
            return (Criteria) this;
        }

        public Criteria andEmail2EqualTo(String value) {
            addCriterion("EMAIL2 =", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotEqualTo(String value) {
            addCriterion("EMAIL2 <>", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2GreaterThan(String value) {
            addCriterion("EMAIL2 >", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2GreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL2 >=", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2LessThan(String value) {
            addCriterion("EMAIL2 <", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2LessThanOrEqualTo(String value) {
            addCriterion("EMAIL2 <=", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2Like(String value) {
            addCriterion("EMAIL2 like", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotLike(String value) {
            addCriterion("EMAIL2 not like", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2In(List<String> values) {
            addCriterion("EMAIL2 in", values, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotIn(List<String> values) {
            addCriterion("EMAIL2 not in", values, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2Between(String value1, String value2) {
            addCriterion("EMAIL2 between", value1, value2, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotBetween(String value1, String value2) {
            addCriterion("EMAIL2 not between", value1, value2, "email2");
            return (Criteria) this;
        }

        public Criteria andCorporationNoIsNull() {
            addCriterion("CORPORATION_NO is null");
            return (Criteria) this;
        }

        public Criteria andCorporationNoIsNotNull() {
            addCriterion("CORPORATION_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCorporationNoEqualTo(String value) {
            addCriterion("CORPORATION_NO =", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoNotEqualTo(String value) {
            addCriterion("CORPORATION_NO <>", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoGreaterThan(String value) {
            addCriterion("CORPORATION_NO >", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoGreaterThanOrEqualTo(String value) {
            addCriterion("CORPORATION_NO >=", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoLessThan(String value) {
            addCriterion("CORPORATION_NO <", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoLessThanOrEqualTo(String value) {
            addCriterion("CORPORATION_NO <=", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoLike(String value) {
            addCriterion("CORPORATION_NO like", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoNotLike(String value) {
            addCriterion("CORPORATION_NO not like", value, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoIn(List<String> values) {
            addCriterion("CORPORATION_NO in", values, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoNotIn(List<String> values) {
            addCriterion("CORPORATION_NO not in", values, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoBetween(String value1, String value2) {
            addCriterion("CORPORATION_NO between", value1, value2, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andCorporationNoNotBetween(String value1, String value2) {
            addCriterion("CORPORATION_NO not between", value1, value2, "corporationNo");
            return (Criteria) this;
        }

        public Criteria andDepartCdIsNull() {
            addCriterion("DEPART_CD is null");
            return (Criteria) this;
        }

        public Criteria andDepartCdIsNotNull() {
            addCriterion("DEPART_CD is not null");
            return (Criteria) this;
        }

        public Criteria andDepartCdEqualTo(String value) {
            addCriterion("DEPART_CD =", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdNotEqualTo(String value) {
            addCriterion("DEPART_CD <>", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdGreaterThan(String value) {
            addCriterion("DEPART_CD >", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPART_CD >=", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdLessThan(String value) {
            addCriterion("DEPART_CD <", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdLessThanOrEqualTo(String value) {
            addCriterion("DEPART_CD <=", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdLike(String value) {
            addCriterion("DEPART_CD like", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdNotLike(String value) {
            addCriterion("DEPART_CD not like", value, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdIn(List<String> values) {
            addCriterion("DEPART_CD in", values, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdNotIn(List<String> values) {
            addCriterion("DEPART_CD not in", values, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdBetween(String value1, String value2) {
            addCriterion("DEPART_CD between", value1, value2, "departCd");
            return (Criteria) this;
        }

        public Criteria andDepartCdNotBetween(String value1, String value2) {
            addCriterion("DEPART_CD not between", value1, value2, "departCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdIsNull() {
            addCriterion("DIVISION_CD is null");
            return (Criteria) this;
        }

        public Criteria andDivisionCdIsNotNull() {
            addCriterion("DIVISION_CD is not null");
            return (Criteria) this;
        }

        public Criteria andDivisionCdEqualTo(String value) {
            addCriterion("DIVISION_CD =", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdNotEqualTo(String value) {
            addCriterion("DIVISION_CD <>", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdGreaterThan(String value) {
            addCriterion("DIVISION_CD >", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdGreaterThanOrEqualTo(String value) {
            addCriterion("DIVISION_CD >=", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdLessThan(String value) {
            addCriterion("DIVISION_CD <", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdLessThanOrEqualTo(String value) {
            addCriterion("DIVISION_CD <=", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdLike(String value) {
            addCriterion("DIVISION_CD like", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdNotLike(String value) {
            addCriterion("DIVISION_CD not like", value, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdIn(List<String> values) {
            addCriterion("DIVISION_CD in", values, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdNotIn(List<String> values) {
            addCriterion("DIVISION_CD not in", values, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdBetween(String value1, String value2) {
            addCriterion("DIVISION_CD between", value1, value2, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andDivisionCdNotBetween(String value1, String value2) {
            addCriterion("DIVISION_CD not between", value1, value2, "divisionCd");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andActionflgIsNull() {
            addCriterion("ACTIONFLG is null");
            return (Criteria) this;
        }

        public Criteria andActionflgIsNotNull() {
            addCriterion("ACTIONFLG is not null");
            return (Criteria) this;
        }

        public Criteria andActionflgEqualTo(String value) {
            addCriterion("ACTIONFLG =", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgNotEqualTo(String value) {
            addCriterion("ACTIONFLG <>", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgGreaterThan(String value) {
            addCriterion("ACTIONFLG >", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIONFLG >=", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgLessThan(String value) {
            addCriterion("ACTIONFLG <", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgLessThanOrEqualTo(String value) {
            addCriterion("ACTIONFLG <=", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgLike(String value) {
            addCriterion("ACTIONFLG like", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgNotLike(String value) {
            addCriterion("ACTIONFLG not like", value, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgIn(List<String> values) {
            addCriterion("ACTIONFLG in", values, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgNotIn(List<String> values) {
            addCriterion("ACTIONFLG not in", values, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgBetween(String value1, String value2) {
            addCriterion("ACTIONFLG between", value1, value2, "actionflg");
            return (Criteria) this;
        }

        public Criteria andActionflgNotBetween(String value1, String value2) {
            addCriterion("ACTIONFLG not between", value1, value2, "actionflg");
            return (Criteria) this;
        }

        public Criteria andRegUserIdIsNull() {
            addCriterion("REG_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegUserIdIsNotNull() {
            addCriterion("REG_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegUserIdEqualTo(String value) {
            addCriterion("REG_USER_ID =", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotEqualTo(String value) {
            addCriterion("REG_USER_ID <>", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdGreaterThan(String value) {
            addCriterion("REG_USER_ID >", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("REG_USER_ID >=", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdLessThan(String value) {
            addCriterion("REG_USER_ID <", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdLessThanOrEqualTo(String value) {
            addCriterion("REG_USER_ID <=", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdLike(String value) {
            addCriterion("REG_USER_ID like", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotLike(String value) {
            addCriterion("REG_USER_ID not like", value, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdIn(List<String> values) {
            addCriterion("REG_USER_ID in", values, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotIn(List<String> values) {
            addCriterion("REG_USER_ID not in", values, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdBetween(String value1, String value2) {
            addCriterion("REG_USER_ID between", value1, value2, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegUserIdNotBetween(String value1, String value2) {
            addCriterion("REG_USER_ID not between", value1, value2, "regUserId");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeIsNull() {
            addCriterion("REG_DATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeIsNotNull() {
            addCriterion("REG_DATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeEqualTo(Date value) {
            addCriterion("REG_DATE_TIME =", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeNotEqualTo(Date value) {
            addCriterion("REG_DATE_TIME <>", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeGreaterThan(Date value) {
            addCriterion("REG_DATE_TIME >", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DATE_TIME >=", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeLessThan(Date value) {
            addCriterion("REG_DATE_TIME <", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("REG_DATE_TIME <=", value, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeIn(List<Date> values) {
            addCriterion("REG_DATE_TIME in", values, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeNotIn(List<Date> values) {
            addCriterion("REG_DATE_TIME not in", values, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeBetween(Date value1, Date value2) {
            addCriterion("REG_DATE_TIME between", value1, value2, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andRegDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("REG_DATE_TIME not between", value1, value2, "regDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNull() {
            addCriterion("UPD_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNotNull() {
            addCriterion("UPD_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdEqualTo(String value) {
            addCriterion("UPD_USER_ID =", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotEqualTo(String value) {
            addCriterion("UPD_USER_ID <>", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThan(String value) {
            addCriterion("UPD_USER_ID >", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPD_USER_ID >=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThan(String value) {
            addCriterion("UPD_USER_ID <", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPD_USER_ID <=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLike(String value) {
            addCriterion("UPD_USER_ID like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotLike(String value) {
            addCriterion("UPD_USER_ID not like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIn(List<String> values) {
            addCriterion("UPD_USER_ID in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotIn(List<String> values) {
            addCriterion("UPD_USER_ID not in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdBetween(String value1, String value2) {
            addCriterion("UPD_USER_ID between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("UPD_USER_ID not between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeIsNull() {
            addCriterion("UPD_DATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeIsNotNull() {
            addCriterion("UPD_DATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME =", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeNotEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME <>", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeGreaterThan(Date value) {
            addCriterion("UPD_DATE_TIME >", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME >=", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeLessThan(Date value) {
            addCriterion("UPD_DATE_TIME <", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DATE_TIME <=", value, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeIn(List<Date> values) {
            addCriterion("UPD_DATE_TIME in", values, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeNotIn(List<Date> values) {
            addCriterion("UPD_DATE_TIME not in", values, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeBetween(Date value1, Date value2) {
            addCriterion("UPD_DATE_TIME between", value1, value2, "updDateTime");
            return (Criteria) this;
        }

        public Criteria andUpdDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DATE_TIME not between", value1, value2, "updDateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_user
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 25 18:46:10 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}