package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class MstUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.USER_NM
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String userNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.PWD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String roleCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.SEX
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.BIRTHDAY
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.ADDRESS
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.TEL_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.MOBILE_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.EMAIL1
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String email1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.EMAIL2
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String email2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.CORPORATION_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String corporationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.DEPART_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String departCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.DIVISION_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String divisionCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.REMARK
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.ACTIONFLG
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String actionflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.REG_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String regUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private Date regDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private String updUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private Date updDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.USER_ID
     *
     * @return the value of mst_user.USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.USER_ID
     *
     * @param userId the value for mst_user.USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.USER_NM
     *
     * @return the value of mst_user.USER_NM
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getUserNm() {
        return userNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.USER_NM
     *
     * @param userNm the value for mst_user.USER_NM
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setUserNm(String userNm) {
        this.userNm = userNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.PWD
     *
     * @return the value of mst_user.PWD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.PWD
     *
     * @param pwd the value for mst_user.PWD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.ROLE_CD
     *
     * @return the value of mst_user.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.ROLE_CD
     *
     * @param roleCd the value for mst_user.ROLE_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.SEX
     *
     * @return the value of mst_user.SEX
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.SEX
     *
     * @param sex the value for mst_user.SEX
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.BIRTHDAY
     *
     * @return the value of mst_user.BIRTHDAY
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.BIRTHDAY
     *
     * @param birthday the value for mst_user.BIRTHDAY
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.ADDRESS
     *
     * @return the value of mst_user.ADDRESS
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.ADDRESS
     *
     * @param address the value for mst_user.ADDRESS
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.TEL_NO
     *
     * @return the value of mst_user.TEL_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.TEL_NO
     *
     * @param telNo the value for mst_user.TEL_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.MOBILE_NO
     *
     * @return the value of mst_user.MOBILE_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.MOBILE_NO
     *
     * @param mobileNo the value for mst_user.MOBILE_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.EMAIL1
     *
     * @return the value of mst_user.EMAIL1
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.EMAIL1
     *
     * @param email1 the value for mst_user.EMAIL1
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.EMAIL2
     *
     * @return the value of mst_user.EMAIL2
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.EMAIL2
     *
     * @param email2 the value for mst_user.EMAIL2
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.CORPORATION_NO
     *
     * @return the value of mst_user.CORPORATION_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getCorporationNo() {
        return corporationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.CORPORATION_NO
     *
     * @param corporationNo the value for mst_user.CORPORATION_NO
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setCorporationNo(String corporationNo) {
        this.corporationNo = corporationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.DEPART_CD
     *
     * @return the value of mst_user.DEPART_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getDepartCd() {
        return departCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.DEPART_CD
     *
     * @param departCd the value for mst_user.DEPART_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setDepartCd(String departCd) {
        this.departCd = departCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.DIVISION_CD
     *
     * @return the value of mst_user.DIVISION_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getDivisionCd() {
        return divisionCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.DIVISION_CD
     *
     * @param divisionCd the value for mst_user.DIVISION_CD
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setDivisionCd(String divisionCd) {
        this.divisionCd = divisionCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.REMARK
     *
     * @return the value of mst_user.REMARK
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.REMARK
     *
     * @param remark the value for mst_user.REMARK
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.ACTIONFLG
     *
     * @return the value of mst_user.ACTIONFLG
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getActionflg() {
        return actionflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.ACTIONFLG
     *
     * @param actionflg the value for mst_user.ACTIONFLG
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setActionflg(String actionflg) {
        this.actionflg = actionflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.REG_USER_ID
     *
     * @return the value of mst_user.REG_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getRegUserId() {
        return regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.REG_USER_ID
     *
     * @param regUserId the value for mst_user.REG_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRegUserId(String regUserId) {
        this.regUserId = regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.REG_DATE_TIME
     *
     * @return the value of mst_user.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public Date getRegDateTime() {
        return regDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.REG_DATE_TIME
     *
     * @param regDateTime the value for mst_user.REG_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setRegDateTime(Date regDateTime) {
        this.regDateTime = regDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.UPD_USER_ID
     *
     * @return the value of mst_user.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public String getUpdUserId() {
        return updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.UPD_USER_ID
     *
     * @param updUserId the value for mst_user.UPD_USER_ID
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_user.UPD_DATE_TIME
     *
     * @return the value of mst_user.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public Date getUpdDateTime() {
        return updDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_user.UPD_DATE_TIME
     *
     * @param updDateTime the value for mst_user.UPD_DATE_TIME
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    public void setUpdDateTime(Date updDateTime) {
        this.updDateTime = updDateTime;
    }
}