package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class TblAudioFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_audio_file.audio_file_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String audioFileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_audio_file.audio_file_url
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String audioFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_audio_file.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String updUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_audio_file.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_audio_file
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audio_file.audio_file_no
     *
     * @return the value of tbl_audio_file.audio_file_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getAudioFileNo() {
        return audioFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audio_file.audio_file_no
     *
     * @param audioFileNo the value for tbl_audio_file.audio_file_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setAudioFileNo(String audioFileNo) {
        this.audioFileNo = audioFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audio_file.audio_file_url
     *
     * @return the value of tbl_audio_file.audio_file_url
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getAudioFileUrl() {
        return audioFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audio_file.audio_file_url
     *
     * @param audioFileUrl the value for tbl_audio_file.audio_file_url
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setAudioFileUrl(String audioFileUrl) {
        this.audioFileUrl = audioFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audio_file.upd_user_id
     *
     * @return the value of tbl_audio_file.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getUpdUserId() {
        return updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audio_file.upd_user_id
     *
     * @param updUserId the value for tbl_audio_file.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audio_file.upd_time
     *
     * @return the value of tbl_audio_file.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audio_file.upd_time
     *
     * @param updTime the value for tbl_audio_file.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }
}