package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;

public class TblBook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.book_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String bookNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.book_Name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.book_no
     *
     * @return the value of tbl_book.book_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getBookNo() {
        return bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.book_no
     *
     * @param bookNo the value for tbl_book.book_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setBookNo(String bookNo) {
        this.bookNo = bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.book_Name
     *
     * @return the value of tbl_book.book_Name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.book_Name
     *
     * @param bookName the value for tbl_book.book_Name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
}