package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;

public class TblDirectKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_direct.book_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String bookNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_direct.lesson_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String lessonNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_direct
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_direct.book_no
     *
     * @return the value of tbl_direct.book_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getBookNo() {
        return bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_direct.book_no
     *
     * @param bookNo the value for tbl_direct.book_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setBookNo(String bookNo) {
        this.bookNo = bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_direct.lesson_no
     *
     * @return the value of tbl_direct.lesson_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getLessonNo() {
        return lessonNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_direct.lesson_no
     *
     * @param lessonNo the value for tbl_direct.lesson_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setLessonNo(String lessonNo) {
        this.lessonNo = lessonNo;
    }
}