package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class TblExpression2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_expression2.exp_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String expId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_expression2.exp_topic
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String expTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_expression2.exp_size
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private Long expSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_expression2.exp_del_flg
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String expDelFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_expression2.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String updUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_expression2.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private Date updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_expression2.exp_example
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private byte[] expExample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_expression2
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_expression2.exp_id
     *
     * @return the value of tbl_expression2.exp_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getExpId() {
        return expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_expression2.exp_id
     *
     * @param expId the value for tbl_expression2.exp_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setExpId(String expId) {
        this.expId = expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_expression2.exp_topic
     *
     * @return the value of tbl_expression2.exp_topic
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getExpTopic() {
        return expTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_expression2.exp_topic
     *
     * @param expTopic the value for tbl_expression2.exp_topic
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setExpTopic(String expTopic) {
        this.expTopic = expTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_expression2.exp_size
     *
     * @return the value of tbl_expression2.exp_size
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Long getExpSize() {
        return expSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_expression2.exp_size
     *
     * @param expSize the value for tbl_expression2.exp_size
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setExpSize(Long expSize) {
        this.expSize = expSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_expression2.exp_del_flg
     *
     * @return the value of tbl_expression2.exp_del_flg
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getExpDelFlg() {
        return expDelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_expression2.exp_del_flg
     *
     * @param expDelFlg the value for tbl_expression2.exp_del_flg
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setExpDelFlg(String expDelFlg) {
        this.expDelFlg = expDelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_expression2.upd_user_id
     *
     * @return the value of tbl_expression2.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getUpdUserId() {
        return updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_expression2.upd_user_id
     *
     * @param updUserId the value for tbl_expression2.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_expression2.upd_time
     *
     * @return the value of tbl_expression2.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_expression2.upd_time
     *
     * @param updTime the value for tbl_expression2.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_expression2.exp_example
     *
     * @return the value of tbl_expression2.exp_example
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public byte[] getExpExample() {
        return expExample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_expression2.exp_example
     *
     * @param expExample the value for tbl_expression2.exp_example
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setExpExample(byte[] expExample) {
        this.expExample = expExample;
    }
}