package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;

public class TblLession implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lession.lession_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String lessionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lession.lession_Name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String lessionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lession.lession_no
     *
     * @return the value of tbl_lession.lession_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getLessionNo() {
        return lessionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lession.lession_no
     *
     * @param lessionNo the value for tbl_lession.lession_no
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setLessionNo(String lessionNo) {
        this.lessionNo = lessionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lession.lession_Name
     *
     * @return the value of tbl_lession.lession_Name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getLessionName() {
        return lessionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lession.lession_Name
     *
     * @param lessionName the value for tbl_lession.lession_Name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setLessionName(String lessionName) {
        this.lessionName = lessionName;
    }
}