package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class TblLessionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public TblLessionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLessionNoIsNull() {
            addCriterion("lession_no is null");
            return (Criteria) this;
        }

        public Criteria andLessionNoIsNotNull() {
            addCriterion("lession_no is not null");
            return (Criteria) this;
        }

        public Criteria andLessionNoEqualTo(String value) {
            addCriterion("lession_no =", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoNotEqualTo(String value) {
            addCriterion("lession_no <>", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoGreaterThan(String value) {
            addCriterion("lession_no >", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoGreaterThanOrEqualTo(String value) {
            addCriterion("lession_no >=", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoLessThan(String value) {
            addCriterion("lession_no <", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoLessThanOrEqualTo(String value) {
            addCriterion("lession_no <=", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoLike(String value) {
            addCriterion("lession_no like", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoNotLike(String value) {
            addCriterion("lession_no not like", value, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoIn(List<String> values) {
            addCriterion("lession_no in", values, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoNotIn(List<String> values) {
            addCriterion("lession_no not in", values, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoBetween(String value1, String value2) {
            addCriterion("lession_no between", value1, value2, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNoNotBetween(String value1, String value2) {
            addCriterion("lession_no not between", value1, value2, "lessionNo");
            return (Criteria) this;
        }

        public Criteria andLessionNameIsNull() {
            addCriterion("lession_Name is null");
            return (Criteria) this;
        }

        public Criteria andLessionNameIsNotNull() {
            addCriterion("lession_Name is not null");
            return (Criteria) this;
        }

        public Criteria andLessionNameEqualTo(String value) {
            addCriterion("lession_Name =", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameNotEqualTo(String value) {
            addCriterion("lession_Name <>", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameGreaterThan(String value) {
            addCriterion("lession_Name >", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameGreaterThanOrEqualTo(String value) {
            addCriterion("lession_Name >=", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameLessThan(String value) {
            addCriterion("lession_Name <", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameLessThanOrEqualTo(String value) {
            addCriterion("lession_Name <=", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameLike(String value) {
            addCriterion("lession_Name like", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameNotLike(String value) {
            addCriterion("lession_Name not like", value, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameIn(List<String> values) {
            addCriterion("lession_Name in", values, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameNotIn(List<String> values) {
            addCriterion("lession_Name not in", values, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameBetween(String value1, String value2) {
            addCriterion("lession_Name between", value1, value2, "lessionName");
            return (Criteria) this;
        }

        public Criteria andLessionNameNotBetween(String value1, String value2) {
            addCriterion("lession_Name not between", value1, value2, "lessionName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_lession
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 02 19:48:22 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_lession
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}