package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class TblText extends TblTextKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_text.text_size
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private Long textSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_text.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String updUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_text.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private Date updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_text.text_data
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private byte[] textData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_text.text_size
     *
     * @return the value of tbl_text.text_size
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Long getTextSize() {
        return textSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_text.text_size
     *
     * @param textSize the value for tbl_text.text_size
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setTextSize(Long textSize) {
        this.textSize = textSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_text.upd_user_id
     *
     * @return the value of tbl_text.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getUpdUserId() {
        return updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_text.upd_user_id
     *
     * @param updUserId the value for tbl_text.upd_user_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_text.upd_time
     *
     * @return the value of tbl_text.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_text.upd_time
     *
     * @param updTime the value for tbl_text.upd_time
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_text.text_data
     *
     * @return the value of tbl_text.text_data
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public byte[] getTextData() {
        return textData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_text.text_data
     *
     * @param textData the value for tbl_text.text_data
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setTextData(byte[] textData) {
        this.textData = textData;
    }
}