package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.io.Serializable;

public class TblTextKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_text.text_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String textId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_text.text_name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private String textName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_text.text_id
     *
     * @return the value of tbl_text.text_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_text.text_id
     *
     * @param textId the value for tbl_text.text_id
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setTextId(String textId) {
        this.textId = textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_text.text_name
     *
     * @return the value of tbl_text.text_name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getTextName() {
        return textName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_text.text_name
     *
     * @param textName the value for tbl_text.text_name
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setTextName(String textName) {
        this.textName = textName;
    }
}