package jp.co.drm.ccp.base.integration.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class TblWordKindExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public TblWordKindExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWordKindIdIsNull() {
            addCriterion("word_kind_id is null");
            return (Criteria) this;
        }

        public Criteria andWordKindIdIsNotNull() {
            addCriterion("word_kind_id is not null");
            return (Criteria) this;
        }

        public Criteria andWordKindIdEqualTo(String value) {
            addCriterion("word_kind_id =", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdNotEqualTo(String value) {
            addCriterion("word_kind_id <>", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdGreaterThan(String value) {
            addCriterion("word_kind_id >", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdGreaterThanOrEqualTo(String value) {
            addCriterion("word_kind_id >=", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdLessThan(String value) {
            addCriterion("word_kind_id <", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdLessThanOrEqualTo(String value) {
            addCriterion("word_kind_id <=", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdLike(String value) {
            addCriterion("word_kind_id like", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdNotLike(String value) {
            addCriterion("word_kind_id not like", value, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdIn(List<String> values) {
            addCriterion("word_kind_id in", values, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdNotIn(List<String> values) {
            addCriterion("word_kind_id not in", values, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdBetween(String value1, String value2) {
            addCriterion("word_kind_id between", value1, value2, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindIdNotBetween(String value1, String value2) {
            addCriterion("word_kind_id not between", value1, value2, "wordKindId");
            return (Criteria) this;
        }

        public Criteria andWordKindNameIsNull() {
            addCriterion("word_kind_name is null");
            return (Criteria) this;
        }

        public Criteria andWordKindNameIsNotNull() {
            addCriterion("word_kind_name is not null");
            return (Criteria) this;
        }

        public Criteria andWordKindNameEqualTo(String value) {
            addCriterion("word_kind_name =", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameNotEqualTo(String value) {
            addCriterion("word_kind_name <>", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameGreaterThan(String value) {
            addCriterion("word_kind_name >", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameGreaterThanOrEqualTo(String value) {
            addCriterion("word_kind_name >=", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameLessThan(String value) {
            addCriterion("word_kind_name <", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameLessThanOrEqualTo(String value) {
            addCriterion("word_kind_name <=", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameLike(String value) {
            addCriterion("word_kind_name like", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameNotLike(String value) {
            addCriterion("word_kind_name not like", value, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameIn(List<String> values) {
            addCriterion("word_kind_name in", values, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameNotIn(List<String> values) {
            addCriterion("word_kind_name not in", values, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameBetween(String value1, String value2) {
            addCriterion("word_kind_name between", value1, value2, "wordKindName");
            return (Criteria) this;
        }

        public Criteria andWordKindNameNotBetween(String value1, String value2) {
            addCriterion("word_kind_name not between", value1, value2, "wordKindName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_word_kind
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 02 19:48:22 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}