package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstCorporation;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstCorporationExample;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstCorporationKey;
import org.apache.ibatis.annotations.Param;

public interface MstCorporationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    long countByExample(MstCorporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int deleteByExample(MstCorporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int deleteByPrimaryKey(MstCorporationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int insert(MstCorporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int insertSelective(MstCorporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    List<MstCorporation> selectByExample(MstCorporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    MstCorporation selectByPrimaryKey(MstCorporationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByExampleSelective(@Param("record") MstCorporation record, @Param("example") MstCorporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByExample(@Param("record") MstCorporation record, @Param("example") MstCorporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByPrimaryKeySelective(MstCorporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_corporation
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByPrimaryKey(MstCorporation record);
}