package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroupRole;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroupRoleExample;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroupRoleKey;
import org.apache.ibatis.annotations.Param;

public interface MstGroupRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    long countByExample(MstGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int deleteByExample(MstGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int deleteByPrimaryKey(MstGroupRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int insert(MstGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int insertSelective(MstGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    List<MstGroupRole> selectByExample(MstGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    MstGroupRole selectByPrimaryKey(MstGroupRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByExampleSelective(@Param("record") MstGroupRole record, @Param("example") MstGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByExample(@Param("record") MstGroupRole record, @Param("example") MstGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByPrimaryKeySelective(MstGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_role
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByPrimaryKey(MstGroupRole record);
}