package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroup;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroupExample;
import org.apache.ibatis.annotations.Param;

public interface MstGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    long countByExample(MstGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int deleteByExample(MstGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int insert(MstGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int insertSelective(MstGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    List<MstGroup> selectByExample(MstGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    MstGroup selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByExampleSelective(@Param("record") MstGroup record, @Param("example") MstGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByExample(@Param("record") MstGroup record, @Param("example") MstGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByPrimaryKeySelective(MstGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByPrimaryKey(MstGroup record);
}