package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroupUser;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroupUserExample;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstGroupUserKey;
import org.apache.ibatis.annotations.Param;

public interface MstGroupUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    long countByExample(MstGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int deleteByExample(MstGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int deleteByPrimaryKey(MstGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int insert(MstGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int insertSelective(MstGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    List<MstGroupUser> selectByExample(MstGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    MstGroupUser selectByPrimaryKey(MstGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByExampleSelective(@Param("record") MstGroupUser record, @Param("example") MstGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByExample(@Param("record") MstGroupUser record, @Param("example") MstGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByPrimaryKeySelective(MstGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_group_user
     *
     * @mbg.generated Fri Aug 25 18:46:10 JST 2017
     */
    int updateByPrimaryKey(MstGroupUser record);
}