package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstUser;
import jp.co.drm.ccp.base.integration.mybatis.entity.MstUserExample;
import org.apache.ibatis.annotations.Param;

public interface MstUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    long countByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int deleteByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int insert(MstUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int insertSelective(MstUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    List<MstUser> selectByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    MstUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByExampleSelective(@Param("record") MstUser record, @Param("example") MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByExample(@Param("record") MstUser record, @Param("example") MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByPrimaryKeySelective(MstUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Fri Aug 18 19:42:30 JST 2017
     */
    int updateByPrimaryKey(MstUser record);
}