package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblBook;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblBookExample;
import org.apache.ibatis.annotations.Param;

public interface TblBookDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    long countByExample(TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int deleteByExample(TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insert(TblBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insertSelective(TblBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    List<TblBook> selectByExample(TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblBook record, @Param("example") TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExample(@Param("record") TblBook record, @Param("example") TblBookExample example);
}