package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblExpression;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblExpressionExample;
import org.apache.ibatis.annotations.Param;

public interface TblExpressionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    long countByExample(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int deleteByExample(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int deleteByPrimaryKey(String expId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insert(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insertSelective(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    List<TblExpression> selectByExampleWithBLOBs(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    List<TblExpression> selectByExample(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    TblExpression selectByPrimaryKey(String expId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblExpression record, @Param("example") TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TblExpression record, @Param("example") TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExample(@Param("record") TblExpression record, @Param("example") TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKeySelective(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKey(TblExpression record);
}