package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblText;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblTextExample;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblTextKey;
import org.apache.ibatis.annotations.Param;

public interface TblTextDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    long countByExample(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int deleteByExample(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int deleteByPrimaryKey(TblTextKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insert(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insertSelective(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    List<TblText> selectByExampleWithBLOBs(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    List<TblText> selectByExample(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    TblText selectByPrimaryKey(TblTextKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblText record, @Param("example") TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TblText record, @Param("example") TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExample(@Param("record") TblText record, @Param("example") TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKeySelective(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKey(TblText record);
}