package jp.co.drm.ccp.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblWord;
import jp.co.drm.ccp.base.integration.mybatis.entity.TblWordExample;
import org.apache.ibatis.annotations.Param;

public interface TblWordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    long countByExample(TblWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int deleteByExample(TblWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int deleteByPrimaryKey(String wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insert(TblWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int insertSelective(TblWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    List<TblWord> selectByExample(TblWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    TblWord selectByPrimaryKey(String wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblWord record, @Param("example") TblWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByExample(@Param("record") TblWord record, @Param("example") TblWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKeySelective(TblWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word
     *
     * @mbg.generated Wed Aug 02 19:48:22 JST 2017
     */
    int updateByPrimaryKey(TblWord record);
}